version: "3.8"

services:
  db:
    image: docker.io/library/postgres:15
    container_name: grpc_todo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: grpc_todo_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
    ports:
      - "3000:3000"
      - "50051:50051"

volumes:
  pgdata:
